### ISSUE TITLE
Error loading new infection data

### ISSUE THREAD

**Issue by nukeador** [RadarCOVID/radar-covid-android#2]
🔑Each time I open the app on Android this is the notification I get

![imagen](https://user-images.githubusercontent.com/531906/92617483-9f174880-f2bf-11ea-9097-f250ea10a949.png)

The updates on the "Exposition data" seems to be stuck on a specific date and the only way to force its update is disabling "Radar Covid Activo" and enable it again. 

Device: Huawei P30
OS: Android 10

**Comment by EsteveSegura** [comment]
Have you compiled the app and tried to make it work?

**Comment by Arasthel** [comment]
It happens quite frequently on Xiaomi devices with MIUI ROM too. Sometimes disabling and enabling exposure notifications in the app is enough, other times I've had to reset that on Settings > Google > Exposure notifications. However, this issue is always back in a day or two.

Device: Xiaomi Mi 9T Pro
OS: Android 10 (MIUI 12.0.1).

**Comment by skgsergio** [comment]
Some ROMs like the ones from Xiaomi or Huawei have aggresive battery saving options.

It stopped giving me that error on a Xiaomi with MIUI 12 once I allowed the App to auto init and disabled battery saving for it. 

![Screenshot_2020-09-09-17-48-37-907_com.miui.securitycenter~2.jpg](https://user-images.githubusercontent.com/186349/92622287-2c10d080-f2c5-11ea-97da-033175eb11b9.jpg)

**Comment by Arasthel** [comment]
No luck in my case: [Screenshot](https://user-images.githubusercontent.com/480955/92622832-cf61e580-f2c5-11ea-9cbb-067a2be23152.jpg)

I will try disabling and enabling notifications again and see if that helps. I just saw that the error shown in that notification can be any of these: https://github.com/RadarCOVID/radar-covid-android/blob/67a4506cc43a20062e87aebd5caa6be2ea0f6482/app/src/main/res/values/strings.xml#L340 
I guess it could be either `R.string. dp3t_sdk_service_notification_error_sync_signature` or `R.string.dp3t_sdk_service_notification_error_sync_api` since it goes away when you disable and re-enable the exposure notifications and those other strings with the same message don't make much sense - no network connection, no server connection, SSL/TLS issues, etc.

I guess I'll try to build it when I have some free time and try to change those strings to see which one is actually appearing.

**Comment by skgsergio** [comment]
Would be more helpful, indeed. As simple as adding some kind of error code/number at the end of the message (or just be more verbose, but I understand that they prefer to keep simple to the user) in order to be able to identify which of the errors is as there are 5 errors that use the same string:

https://github.com/RadarCOVID/radar-covid-android/blob/67a4506cc43a20062e87aebd5caa6be2ea0f6482/app/src/main/res/values/strings.xml#L340-L346

**Comment by zenitraM** [comment]
Also useful depending on your phone model: https://dontkillmyapp.com/

In any case it'd be nice if it warned about needing to disable battery optimizations specifically apart from giving a generic error. The amount of people with Xiaomis/Huaweis that won't know they exist and how to disable those is probably big.

**Comment by nukeador** [comment]
Changing energy mode on Huawei doesn't seem to make a difference. The notification keeps popping each time I open the app.

![imagen](https://user-images.githubusercontent.com/531906/92713717-9aa06d80-f35b-11ea-98e1-7e84b610cfa6.png)

**Comment by devnix** [comment]
I have the same issue in Xiaomi Redmi Note 8T with Android 9, MIUI 11. It only pops up when I open the app (when I installed it and configured power saving for the app, it looked fine).

**Comment by javimurcia** [comment]
I have observed that behaviour when i don't let the app comunicate with the notification server.

Try to force close the app (force close, not deleting its data) and open it normally and see if the app start normally and doesn't complain. I asume that since the app is in the foreground, the os should allow it to comunicate with the internet.

It's a kludge, but it should keep the app "afloat" while they fix the bug. Since the app only downloads the diagnostic keys from the internet, and the actual exchange of keys over bluetooth is handled by the OS (google play services), this should work, so even if the app misbehabe form time to time, if you remember to "wake" te app so it can download the diagnosis keys you should still be notified if you came into close contact with a positive patient (if he chooses to comunicate its test via the app, which sadly no one does)

**Comment by puentev** [comment]
This keeps happening since early betas both in restricted and unrestricted battery mode in latest MIUI 11/12 in multiple Xiaomi devices. Since SEDIA/Indra seems unaware, I would like to indicate  Xiaomi owns the 25% of the market in Spain (and Huawei 20%). Please do the math, and understand the severity of the bug. You can reproduce it easily. In any Xiaomi device I tested it, happened (includes Poco f1/f2, Mi max 3, multiple redmi notes, etc...).

I guess is not back luck to have the worst infection rate in Europe. I hope SEDIA heads will pay in the future, in a penal way, for their profound irresponsibility.

**Comment by skgsergio** [comment]
>  You can reproduce it easily. In any Xiaomi device I tested it, happened (includes Poco f1/f2, Mi max 3, multiple redmi notes, etc...).
@puentev How do you reproduce it? I'm using a Mi 9T Pro with MIUI12 without the issue, I had it in the beginning but not anymore. Just trying to understand if I did something to my phone at some point that helped. I did not open the app in weeks and if I go to the exposure notifications under google settings I get that in the last 14 days it did 174 checks and last was today at 18:35.

Weirdest thing I have is the DNS server changed to use DNS over TLS and since most people on this thread mention that looks like a network communication issue it might have something to do.

**Comment by aalmenar** [comment]
> This keeps happening since early betas both in restricted and unrestricted battery mode in latest MIUI 11/12 (android 10) in multiple Xiaomi devices. Since SEDIA/Indra seems unaware, I would like to indicate Xiaomi owns the 25% of the market in Spain (and Huawei 20%). Please do the math, and understand the severity of the bug. You can reproduce it easily. In any Xiaomi device I tested it, happened (includes Poco f1/f2, Mi max 3, multiple redmi notes, etc...).

Please check German app which also has issues with these brands. It’s not only a Radar Covid issue.

https://github.com/corona-warn-app/cwa-app-android

> 
> I guess is not back luck to have the worst infection rate in Europe. I hope that the responsible at SEDIA pay in the future, in a penal way, for their profound irresponsibility and sloppiness around this app.

I refrain myself from answering these, this is not the place and I think it would be welcome by everyone to keep it based on code, not political opinions. There are plenty of forums for that.

**Comment by puentev** [comment]
> How do you reproduce it? I'm using a Mi 9T Pro with MIUI12 without the issue, I had it in the beginning but not anymore. Just trying to understand if I did something to my phone at some point that helped.

It just happens. In battery restricted mode, is more frequent. In restricted mode it happens, although less frequently. In 14 days I got a few (between 10 and 15 at the same date and hour). Something is not correct there.

> Please check German app which also has issues with these brands. It’s not only a Radar Covid issue.

Can you tell us the specific open issues? Most are from June, and closed.

**Comment by Arasthel** [comment]
In my case, what @skgsergio mentioned before actually helped, I had to enable autostart and disable battery saving for the app. After killing and relaunching the app, the issue seems to be gone.

> Some ROMs like the ones from Xiaomi or Huawei have aggresive battery saving options.
> 
> It stopped giving me that error on a Xiaomi with MIUI 12 once I allowed the App to auto init and disabled battery saving for it.
> 
> ![Screenshot_2020-09-09-17-48-37-907_com.miui.securitycenter~2.jpg](https://user-images.githubusercontent.com/186349/92622287-2c10d080-f2c5-11ea-97da-033175eb11b9.jpg)

**Comment by pantic79** [comment]
Please @Arasthel, could you confirm that your issue is definitively solved?.

Thanks for your contributions.

**Comment by Arasthel** [comment]
> Please @Arasthel, could you confirm that your issue is definitively solved?.
> 
> Thanks for your contributions.

Yes, I haven't seen the error notification since I changed those settings.

**Comment by pantic79** [comment]
Ok, thank you for your answer!.  I'll share this info with the team and propose to include in the radarcovid.gob.es FAQs section.

Thanks.
